For notes on cleaning data effectively

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Once packages are installed we can get to pulling in the data.
Side note: As a test, we create a numpy array from its documentation and plot the results in a histogram. 
See pyprep.py for test run of above.

In [2]:
# Works just fine
# d2021 = pd.DataFrame(np.array([[1, 2, 2], [4, 5, 6], [7, 8, 9]]))
# Error shown below after running
# d2021 = pd.read_excel('2021.xlsx')
# For this we need openpyxl for opening excel files in python. 
# ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
d2021 = pd.DataFrame(pd.read_excel("2022.xlsx"))
d2021.head()

,Date,Time in Bed,Bedtime,SleepLeftNasalPassageway,SleepRightNasalPassageway,LNoseConditionSleep,RNoseConditionSleep,BreathingComfortRatingSleep,Wake Time,BestSleepRating,...,Number of Wakeups,Presence of dreams,Number of Dreams,HeatOn,ACon,Excersise Time (before bed = within 2 hours before sleeping; after = 2 hours after waking; middle = anytime leftover (but not during sleeping)),Notes,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,2022-01-01 00:00:00,22:26:00,22:52:00,50% Blocked,Blocked,Normal,Normal,Disagree,07:15:00,Neither agree nor disagree,...,9.0,Yes,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-02 00:00:00,23:21:00,00:28:00,Open,75% Blocked,Normal,Normal,Agree,08:29:00,Strongly agree,...,7.0,Yes,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-03 00:00:00,22:44:00,00:22:00,Open,Open,Normal,Normal,Strongly agree,07:28:00,Agree,...,3.0,Yes,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01-04 00:00:00,21:53:00,23:04:00,25% Blocked,Open,Normal,Normal,Agree,07:30:00,Somewhat disagree,...,10.0,No,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-05 00:00:00,23:00:00,23:31:00,50% Blocked,Blocked,Dry,Normal,Neither agree nor disagree,07:30:00,Disagree,...,11.0,Yes,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Let's pull in the otehr data set now and clean this up. 
We want both 2021 and 2022 data in one dataframe.

In [3]:
# Read in the data from the excel files as dataframes
d2021 = pd.DataFrame(pd.read_excel("2021.xlsx"))
d2022 = pd.DataFrame(pd.read_excel("2022.xlsx"))

In [4]:
# Select columns of interest from both df
# rename columns in each to same name 
# bind the rows of the columns with same name

d2021 = d2021.iloc[:, np.r_[:3, 9]] # Use ":" to select everything and np.r_[x] to select no sequential columns
d2022 = d2022.iloc[:, np.r_[:3, 9]] # repeat the same selection here nd reassign to the data frame
# To look at the column names use either
# d2022.columns.values 
# d2022.keys()
# We supply a list of all column names from d2022 to replace each column name in d2021 with that of d2022
d2021.columns = d2022.keys()
df = pd.concat([d2021, d2022]) # to bring together the rows of both dataframes into a combined dataframe

In [5]:
# claculate missing values
df.isna().sum()

Date               473
Time in Bed        659
Bedtime            660
BestSleepRating    468
dtype: int64

In [6]:
# subset the data frame 
# df.loc[df["Date"] == "2022-06-24 00:00:00"]
# df.index[df["Date"] == "2022-10-02 00:00:00"]
# df.iloc[:550, :].tail()
# df.loc[df["Date"] == "2022-06-24 00:00:00"]
# type(df["Date"])
df = df.iloc[:546,:] # By hand entering different values until 2022-06-24 was found

In [7]:
# change data types
# impute missing values
# first we check the data types
# One way to check is with this
df.dtypes # all the types are strings/objects 
# Another way is 
df.info() # This also counts the number of non-null observations for each object
# Convert the date to a datetime object
# pd.to_datetime(df['Date'])
# df['Date'].astype('datetime64[ns]')
# pd.to_datetime(df["Date"]) # convert from string object to datetime object reassign to dataframe
df.iloc[1:16] # 2821-01-15 00:00:00	22:08:00	22:44:00	Unknown at position 14
# What do we do about this?

<class 'pandas.core.frame.DataFrame'>
Int64Index: 546 entries, 0 to 174
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             540 non-null    object
 1   Time in Bed      545 non-null    object
 2   Bedtime          544 non-null    object
 3   BestSleepRating  546 non-null    object
dtypes: object(4)
memory usage: 21.3+ KB

                   Date Time in Bed   Bedtime BestSleepRating
1   2021-01-02 00:00:00    22:20:00  22:59:00         Unknown
2   2021-01-03 00:00:00    22:49:00  23:18:00         Unknown
3   2021-01-04 00:00:00    22:40:00  23:15:00         Unknown
4   2021-01-05 00:00:00         NaN       NaN         Unknown
5   2021-01-06 00:00:00    00:18:00  00:34:00         Unknown
6   2021-01-07 00:00:00    22:54:00  23:17:00         Unknown
7   2021-01-08 00:00:00    22:53:00  23:46:00         Unknown
8   2021-01-09 00:00:00    22:55:00  23:26:00         Unknown
9   2021-01-10 00:00:00    22:42:00  23:13:00         Unknown
10  2021-01-11 00:00:00        None       NaN         Unknown
11  2021-01-12 00:00:00    20:54:00  21:32:00         Unknown
12  2021-01-13 00:00:00    22:14:00  22:44:00         Unknown
13  2021-01-14 00:00:00    22:00:00  22:46:00         Unknown
14  2821-01-15 00:00:00    22:08:00  22:44:00         Unknown
15  2021-01-16 00:00:00    22:11:00  22:37:00         Unknown